/*************************************************
Copyright: Baosight Software LTD.co Copyright (c) 2012
Author:     bhy
Version:    1.0
Date:       2024-09-11
Description: 炉成本查询
**************************************************/
//框架头文件
#include "stdafx.h"	 

BM2F_ENTERACE(mmsmqxsdl_inq)

int f_mmsmqxsdl_inq(EIClass * bcls_rec, EIClass * bcls_ret, CDbConnection * conn)
{
	CTracer log(__FUNCTION__); 	//系统日志类定义

	/* 程序内部变量 */
	int doFlag = 0;
	int blkNum = 0;

	CString type_flag = "";

	CString v_from = "";//开始时刻
	CString v_to = "";//开始时刻
	CPageInfo pageInfo;



	/* 实体类定义 */

	/* 数据库SQL操作字符串 */
	CString sqlstr;

	/* 数据库操作类定义 */
	CDbCommand cmd_inq(conn);

	try
	{

		if (bcls_rec->Tables[0].Columns.Contains("START_TIME"))
		{
			v_from = bcls_rec->Tables[0].Rows[0]["START_TIME"].ToString().SubstringNE(0, 8);
		}
		if (bcls_rec->Tables[0].Columns.Contains("END_TIME"))
		{
			v_to = bcls_rec->Tables[0].Rows[0]["END_TIME"].ToString().SubstringNE(0, 8);
		}

		if (bcls_rec->Tables[0].Columns.Contains("BUSI_TYPE"))
		{
			type_flag = bcls_rec->Tables[0].Rows[0]["BUSI_TYPE"].ToString().Trim();
		}


		switch (conn->DatabaseKind)
		{
		case DB_KIND_DB2:				// DB2 数据库（未开Oracle兼容）
		case DB_KIND_DB2_ORACLE:	    // DB2 数据库（开Oracle兼容）
		case DB_KIND_MSSQL:				// MS SQL Server数据库
		case DB_KIND_ORACLE:	        // Oracle 数据库
		default:


			//sqlstr = "select * from V_QX_SDL_BB t where 1=1 ";

			sqlstr = "SELECT"
				" t0_agg.LADLE_CLOSE_TIME,"
				" decode(NVL(t0_agg.CAST_DIV_NO, 0), 0, '回炉', t0_agg.CAST_DIV_NO) as CAST_DIV_NO,"
				" t27.heat_no as AOD_HEAT_NO,"
				" t27.ST_NO,"
				" t0x.SG_GRADE_1,"
				" tcb.f_route1,"
				" t27.HEATNO_PREMELT1,"
				" t27.HEATNO_PREMELT2,"
				" t27.HEATNO_PREMELT3,"
				" t27.HEATNO_PREMELT4,"
				" t21.ACTRESULT AS BOF_ACT_WT,"
				" nvl(t0_agg.TS0000_DEVO_WT_SUM, 0) as TS0000_DEVO_WT_SUM,"
				" nvl(t0_agg.Z_DEV_ALLOY_STEEL_SUM, 0) as Z_DEV_ALLOY_STEEL_SUM,"
				" nvl(case when t27.HEATNO_PREMELT1 like 'F%' then t27.weight_premelt1 else 0 end, 0) +nvl(case when t27.HEATNO_PREMELT2 like 'F%' then t27.weight_premelt2 else 0 end, 0) +nvl(case when t27.HEATNO_PREMELT3 like 'F%' then t27.weight_premelt3 else 0 end, 0)  as F_PREFIX_WT_SUM,"
				" round(nvl(t0_agg.Z_DEV_DEVO_MATCR_SUM, 0), 2) as Z_DEV_DEVO_MATCR_SUM,"
				" round(nvl(t0_agg.Z_DEV_DEVO_MATNI_SUM, 0), 2) as Z_DEV_DEVO_MATNI_SUM,"
				" round(nvl(t0_agg.Z_DEV_DEVO_MATMO_SUM, 0), 2) as Z_DEV_DEVO_MATMO_SUM,"
				" round(nvl(t0_agg.E_DEV_ALLOY_STEEL_SUM, 0), 2) as E_DEV_ALLOY_STEEL_SUM,"
				" t20.ACTRESULT AS EAF_ACT_WT,"
				" round(nvl(t0_agg.E_DEV_DEVO_MATCR_SUM, 0), 2) as E_DEV_DEVO_MATCR_SUM,"
				" round(nvl(t0_agg.E_DEV_DEVO_MATNI_SUM, 0), 2) as E_DEV_DEVO_MATNI_SUM,"
				" round(nvl(t0_agg.E_DEV_DEVO_MATMO_SUM, 0), 2) as E_DEV_DEVO_MATMO_SUM,"
				" t27.LADLE_PRE_LIQUID_WT,"
				" t27f.YR_STICKY_WT,"
				" CASE WHEN t0_agg.Z_DEV_ALLOY_STEEL_SUM = 0 THEN NULL ELSE round((nvl(case when t27.HEATNO_PREMELT1 like 'F%' then t27.weight_premelt1 else 0 end, 0) + nvl(case when t27.HEATNO_PREMELT2 like 'F%' then t27.weight_premelt2 else 0 end, 0) + nvl(case when t27.HEATNO_PREMELT3 like 'F%' then t27.weight_premelt3 else 0 end, 0)) * 100/ t0_agg.Z_DEV_ALLOY_STEEL_SUM, 2) END AS ALLOY_SDL,"
				" CASE WHEN t0_agg.E_DEV_ALLOY_STEEL_SUM = 0 THEN NULL ELSE round(t20.ACTRESULT * 100 / t0_agg.E_DEV_ALLOY_STEEL_SUM, 2) END AS EAF_SDL,"
				" round(nvl(t0_agg.Z_DEV_DEVO_MATCR_SUM, 0) + nvl(t0_agg.E_DEV_DEVO_MATCR_SUM, 0), 2) as YR_MATCR_IN,"
				" round(nvl(t0_agg.Z_DEV_DEVO_MATNI_SUM, 0) + nvl(t0_agg.E_DEV_DEVO_MATNI_SUM, 0), 2) as YR_MATNI_IN,"
				" round(nvl(t0_agg.Z_DEV_DEVO_MATMO_SUM, 0) + nvl(t0_agg.E_DEV_DEVO_MATMO_SUM, 0), 2) as YR_MATMO_IN,"
				" round((nvl(t27.LADLE_PRE_LIQUID_WT, 0) + nvl(t27f.YR_STICKY_WT, 0))*nvl(t24_cr_ni_mo.CR_1, 0)*0.01, 2) as YR_CR_OUT,"
				" round((nvl(t27.LADLE_PRE_LIQUID_WT, 0) + nvl(t27f.YR_STICKY_WT, 0))*nvl(t24_cr_ni_mo.NI_1, 0)*0.01, 2) as YR_NI_OUT,"
				" round((nvl(t27.LADLE_PRE_LIQUID_WT, 0) + nvl(t27f.YR_STICKY_WT, 0))*nvl(t24_cr_ni_mo.MO_1, 0)*0.01, 2) as YR_MO_OUT,"
				" CASE WHEN nvl(t0_agg.Z_DEV_ALLOY_STEEL_SUM, 0) <= 0 and nvl(t0_agg.E_DEV_ALLOY_STEEL_SUM, 0) <= 0 THEN NULL ELSE round((nvl(t27.LADLE_PRE_LIQUID_WT, 0) + nvl(t27f.YR_STICKY_WT, 0)) / (t0_agg.Z_DEV_ALLOY_STEEL_SUM + t0_agg.E_DEV_ALLOY_STEEL_SUM), 2) END as YRY_SDL,"
				" CASE WHEN(t0_agg.Z_DEV_DEVO_MATCR_SUM + nvl(t0_agg.E_DEV_DEVO_MATCR_SUM, 0)) = 0 THEN NULL ELSE round((nvl(t27.LADLE_PRE_LIQUID_WT, 0) + nvl(t27f.YR_STICKY_WT, 0))*nvl(t24_cr_ni_mo.CR_1, 0)*0.01 / (t0_agg.Z_DEV_DEVO_MATCR_SUM + nvl(t0_agg.E_DEV_DEVO_MATCR_SUM, 0)), 2) END as YR_CR_SDL,"
				" CASE WHEN(t0_agg.Z_DEV_DEVO_MATNI_SUM + nvl(t0_agg.E_DEV_DEVO_MATNI_SUM, 0)) = 0 THEN NULL ELSE round((nvl(t27.LADLE_PRE_LIQUID_WT, 0) + nvl(t27f.YR_STICKY_WT, 0))*nvl(t24_cr_ni_mo.NI_1, 0)*0.01 / (t0_agg.Z_DEV_DEVO_MATNI_SUM + nvl(t0_agg.E_DEV_DEVO_MATNI_SUM, 0)), 2) END as YR_NI_SDL,"
				" CASE WHEN(t0_agg.Z_DEV_DEVO_MATMO_SUM + nvl(t0_agg.E_DEV_DEVO_MATMO_SUM, 0)) = 0 THEN NULL ELSE round((nvl(t27.LADLE_PRE_LIQUID_WT, 0) + nvl(t27f.YR_STICKY_WT, 0))*nvl(t24_cr_ni_mo.MO_1, 0)*0.01 / (t0_agg.Z_DEV_DEVO_MATMO_SUM + nvl(t0_agg.E_DEV_DEVO_MATMO_SUM, 0)), 2) END  as YR_MO_SDL,"
				" nvl(t27.LADLE_PRE_LIQUID_WT, 0)*nvl(t24_cr_ni_mo.CR_1, 0)*0.01 as YR_CR_A,"
				" nvl(t27.LADLE_PRE_LIQUID_WT, 0)*nvl(t24_cr_ni_mo.NI_1, 0)*0.01 as YR_NI_A,"
				" nvl(t27.LADLE_PRE_LIQUID_WT, 0)*nvl(t24_cr_ni_mo.MO_1, 0)*0.01 as YR_MO_A,"
				" nvl(t0_agg.A_DEV_ALLOY_STEEL_SUM, 0) as A_DEV_ALLOY_STEEL_SUM,"
				" nvl(t0_agg.A_DEV_DEVO_MATCR_SUM, 0) as A_DEV_DEVO_MATCR_SUM,"
				" nvl(t0_agg.A_DEV_DEVO_MATNI_SUM, 0) as A_DEV_DEVO_MATNI_SUM,"
				" nvl(t0_agg.A_DEV_DEVO_MATMO_SUM, 0) as A_DEV_DEVO_MATMO_SUM,"
				" t27.LADLE_PRE_LIQUID_WT + nvl(t0_agg.A_DEV_ALLOY_STEEL_SUM, 0) AS AOD_METAL_SUM,"
				" t27.ACTRESULT AS AOD_ACT_WT,"
				" t26.STEEL_WT AS LTS_ACT_WT,"
				" t24.MOLTIRON_WT AS LF_ACT_WT,"
				" t0_agg.BIG_LADLE_WT,"
				" t0_agg.POUR_LADLE_WT,"
				" t0_agg.BIG_LADLE_WT - t0_agg.POUR_LADLE_WT AS CB_STEEL_WT,"
				" t0_agg.MAT_ACT_WT,"
				" CASE WHEN(t27.LADLE_PRE_LIQUID_WT + nvl(t0_agg.A_DEV_ALLOY_STEEL_SUM, 0)) = 0 THEN NULL ELSE round((t26.STEEL_WT - 3) / (t27.LADLE_PRE_LIQUID_WT + nvl(t0_agg.A_DEV_ALLOY_STEEL_SUM, 0)), 2) END AS AOD_METAL_SDL,"
				" CASE WHEN t26.STEEL_WT = 0 THEN NULL ELSE round(t0_agg.MAT_ACT_WT / t26.STEEL_WT, 2) END AS CCM_SLAB_SDL,"
				" (t0_agg.QIE_T + t0_agg.QIE_W) / 1000 AS CUT_SCRAP_WT,"
				" t0_agg.TD_CSTEEL,"
				" t0_agg.CR_CP,"
				" t0_agg.NI_CP,"
				" t0_agg.MO_CP,"
				" t26.STEEL_WT*t0_agg.CR_CP AS STEEL_CR_OUT,"
				" t26.STEEL_WT*t0_agg.NI_CP AS STEEL_NI_OUT,"
				" t26.STEEL_WT*t0_agg.MO_CP AS STEEL_MO_OUT,"
				" CASE WHEN(t27.LADLE_PRE_LIQUID_WT * nvl(t24_cr_ni_mo.CR_1, 0) + nvl(t0_agg.A_DEV_DEVO_MATCR_SUM, 0)) = 0 THEN NULL ELSE round(t26.STEEL_WT * t0_agg.CR_CP/ (t27.LADLE_PRE_LIQUID_WT * nvl(t24_cr_ni_mo.CR_1, 0) + nvl(t0_agg.A_DEV_DEVO_MATCR_SUM, 0)), 2) END as A_CR_SDL_STEEL,"
				" CASE WHEN(t27.LADLE_PRE_LIQUID_WT * nvl(t24_cr_ni_mo.NI_1, 0) + nvl(t0_agg.A_DEV_DEVO_MATNI_SUM, 0)) = 0 THEN NULL ELSE round(t26.STEEL_WT * t0_agg.NI_CP/ (t27.LADLE_PRE_LIQUID_WT * nvl(t24_cr_ni_mo.NI_1, 0) + nvl(t0_agg.A_DEV_DEVO_MATNI_SUM, 0)), 2) END as A_NI_SDL_STEEL,"
				" CASE WHEN(t27.LADLE_PRE_LIQUID_WT * nvl(t24_cr_ni_mo.MO_1, 0) + nvl(t0_agg.A_DEV_DEVO_MATMO_SUM, 0)) = 0 THEN NULL ELSE round(t26.STEEL_WT * t0_agg.MO_CP/ (t27.LADLE_PRE_LIQUID_WT * nvl(t24_cr_ni_mo.MO_1, 0) + nvl(t0_agg.A_DEV_DEVO_MATMO_SUM, 0)), 2) END as A_MO_SDL_STEEL,"
				" nvl(t0_agg.Q_DEV_ALLOY_STEEL_SUM, 0) as Q_DEV_ALLOY_STEEL_SUM,"
				" nvl(t0_agg.Q_DEV_DEVO_MATCR_SUM, 0) as Q_DEV_DEVO_MATCR_SUM,"
				" nvl(t0_agg.Q_DEV_DEVO_MATNI_SUM, 0) as Q_DEV_DEVO_MATNI_SUM,"
				" nvl(t0_agg.Q_DEV_DEVO_MATMO_SUM, 0) as Q_DEV_DEVO_MATMO_SUM,"
				" (t0_agg.MAT_ACT_WT + (t0_agg.QIE_T + t0_agg.QIE_W) / 1000 + t0_agg.TD_CSTEEL)*t0_agg.CR_CP AS CCM_SLAB_CR_OUT,"
				" (t0_agg.MAT_ACT_WT + (t0_agg.QIE_T + t0_agg.QIE_W) / 1000 + t0_agg.TD_CSTEEL)*t0_agg.NI_CP AS CCM_SLAB_NI_OUT,"
				" (t0_agg.MAT_ACT_WT + (t0_agg.QIE_T + t0_agg.QIE_W) / 1000 + t0_agg.TD_CSTEEL)*t0_agg.MO_CP AS CCM_SLAB_MO_OUT,"
				" CASE WHEN nvl(t0_agg.Q_DEV_DEVO_MATCR_SUM, 0) = 0 THEN NULL ELSE round((t0_agg.MAT_ACT_WT + (t0_agg.QIE_T + t0_agg.QIE_W) / 1000 + t0_agg.TD_CSTEEL)*t0_agg.CR_CP/ nvl(t0_agg.Q_DEV_DEVO_MATCR_SUM, 0), 2) END AS Q_CCM_SLAB_CR_SDL,"
				" CASE WHEN nvl(t0_agg.Q_DEV_DEVO_MATNI_SUM, 0) = 0 THEN NULL ELSE round((t0_agg.MAT_ACT_WT + (t0_agg.QIE_T + t0_agg.QIE_W) / 1000 + t0_agg.TD_CSTEEL)*t0_agg.NI_CP/ nvl(t0_agg.Q_DEV_DEVO_MATNI_SUM, 0), 2) END AS Q_CCM_SLAB_NI_SDL,"
				" CASE WHEN nvl(t0_agg.Q_DEV_DEVO_MATMO_SUM, 0) = 0 THEN NULL ELSE round((t0_agg.MAT_ACT_WT + (t0_agg.QIE_T + t0_agg.QIE_W) / 1000 + t0_agg.TD_CSTEEL)*t0_agg.MO_CP/ nvl(t0_agg.Q_DEV_DEVO_MATMO_SUM, 0), 2) END AS Q_CCM_SLAB_MO_SDL,"
				" CASE WHEN nvl(t0_agg.Q_DEV_ALLOY_STEEL_SUM, 0) = 0 THEN NULL ELSE round((t0_agg.BIG_LADLE_WT - t0_agg.POUR_LADLE_WT)/ nvl(t0_agg.Q_DEV_ALLOY_STEEL_SUM, 0), 2) END as Q_METAL_CB_SDL,"
				" CASE WHEN nvl(t0_agg.Q_DEV_DEVO_MATCR_SUM, 0) = 0 THEN NULL ELSE round((t0_agg.BIG_LADLE_WT - t0_agg.POUR_LADLE_WT) * t0_agg.CR_CP/ nvl(t0_agg.Q_DEV_DEVO_MATCR_SUM, 0), 2) END as Q_CB_CR_SDL,"
				" CASE WHEN nvl(t0_agg.Q_DEV_DEVO_MATNI_SUM, 0) = 0 THEN NULL ELSE round((t0_agg.BIG_LADLE_WT - t0_agg.POUR_LADLE_WT) * t0_agg.NI_CP/ nvl(t0_agg.Q_DEV_DEVO_MATNI_SUM, 0), 2) END as Q_CB_NI_SDL,"
				" CASE WHEN nvl(t0_agg.Q_DEV_DEVO_MATMO_SUM, 0) = 0 THEN NULL ELSE round((t0_agg.BIG_LADLE_WT - t0_agg.POUR_LADLE_WT) * t0_agg.MO_CP/ nvl(t0_agg.Q_DEV_DEVO_MATMO_SUM, 0), 2) END as Q_CB_MO_SDL,"
				" t27f.out_end_radio,"
				" nvl(t24_si2.SI_2, 0) as SI_2,"
				" nvl(t24_si3.SI_3, 0) as SI_3,"
				" t27f.is_back_blow,"
				" t27f.back_blow_o2,"
				" t26.LADLE_ARRIVE_STEEL_WT,"
				" t26.STEEL_WT AS LADLE_GO_STEEL_WT,"
				" t26f.deslag_wt1,"
				" nvl(t0_agg.S_DEV_F_MAT_SUM, 0) as S_DEV_F_MAT_SUM,"
				" nvl(t0_agg.F_DEV_F_MAT_SUM, 0) as F_DEV_F_MAT_SUM,"
				" t26.EMPTY_LADLE_WEIGHT,"
				" t0_agg.POUR_LADLE_WT - t0_agg.BIG_LADLE_TARE_WT AS TUI_STEEL_WT,"
				" t27f.h_cr_bin_sum,"
				" nvl(t0_agg.A_DEV_AB070665_DEVO_WT_SUM, 0) as A_DEV_AB070665_DEVO_WT_SUM,"
				" nvl(t0_agg.Z_DEV_AB070665_DEVO_WT_SUM, 0) as Z_DEV_AB070665_DEVO_WT_SUM,"
				" T20.REMARK AS EAF_REMARK,"
				" T27.REMARK AS AOD_REMARK,"
				" T24.REMARK AS LF_REMARK,"
				" t0_agg.CCM_REMARK"
				" FROM("
				" SELECT"
				" t1.CR_CP,"
				" t1.NI_CP,"
				" t1.MO_CP,"
				" t1.MAT_ACT_WT,"
				" t1.LADLE_CLOSE_TIME,"
				" t1.BIG_LADLE_WT,"
				" t1.POUR_LADLE_WT,"
				" t1.BIG_LADLE_TARE_WT,"
				" t1.TD_CSTEEL,"
				" t1.QIE_T,"
				" t1.QIE_W,"
				" t1.CCM_REMARK,"
				" t1.heat_no,"
				" t1.CAST_DIV_NO,"
				" a_agg.TS0000_DEVO_WT_SUM,"
				" a_agg.Z_DEV_ALLOY_STEEL_SUM,"
				" a_agg.Z_DEV_DEVO_MATCR_SUM,"
				" a_agg.Z_DEV_DEVO_MATNI_SUM,"
				" a_agg.Z_DEV_DEVO_MATMO_SUM,"
				" a_agg.E_DEV_ALLOY_STEEL_SUM,"
				" a_agg.E_DEV_DEVO_MATCR_SUM,"
				" a_agg.E_DEV_DEVO_MATNI_SUM,"
				" a_agg.E_DEV_DEVO_MATMO_SUM,"
				" a_agg.A_DEV_ALLOY_STEEL_SUM,"
				" a_agg.A_DEV_DEVO_MATCR_SUM,"
				" a_agg.A_DEV_DEVO_MATNI_SUM,"
				" a_agg.A_DEV_DEVO_MATMO_SUM,"
				" a_agg.Q_DEV_ALLOY_STEEL_SUM,"
				" a_agg.Q_DEV_DEVO_MATCR_SUM,"
				" a_agg.Q_DEV_DEVO_MATNI_SUM,"
				" a_agg.Q_DEV_DEVO_MATMO_SUM,"
				" a_agg.S_DEV_F_MAT_SUM,"
				" a_agg.F_DEV_F_MAT_SUM,"
				" a_agg.A_DEV_AB070665_DEVO_WT_SUM,"
				" a_agg.Z_DEV_AB070665_DEVO_WT_SUM"
				" FROM("
				" select"
				" t31.CR_CP,"
				" t31.NI_CP,"
				" t31.MO_CP,"
				" nvl((select SUM(MAT_ACT_WT) FROM VMMSMCPCL_BB B where B.heat_no = t31.heat_no and b.SLAB_CUT_TIME <= @v_to and b.SLAB_CUT_TIME >=@v_from), 0) AS MAT_ACT_WT,"
				" t4.LADLE_CLOSE_TIME,"
				" t4.BIG_LADLE_WT,"
				" t4.POUR_LADLE_WT,"
				" t4.BIG_LADLE_TARE_WT,"
				" t4.TD_CSTEEL,"
				" t4.QIE_T,"
				" t4.QIE_W,"
				" t4.CCM_REMARK,"
				" t31.heat_no,"
				" t31.CAST_DIV_NO"
				" from("
				" select"
				" LADLE_CLOSE_TIME,"
				" BIG_LADLE_WT,"
				" POUR_LADLE_WT,"
				" BIG_LADLE_TARE_WT,"
				" TD_CSTEEL,"
				" QIE_T,"
				" QIE_W,"
				" CCM_REMARK,"
				" HEAT_NO"
				" from tmmsm31f"
				" WHERE LADLE_CLOSE_TIME <= @v_to"
				" AND LADLE_CLOSE_TIME >=@v_from) t4"
				" left join("
				" select"
				" F.heat_no, F.CAST_DIV_NO,"
				" H.ELM_006,"
				" H.ELM_007,"
				" H.ELM_008,"
				" NVL(CASE WHEN H.ELM_006 = -1 THEN 0 ELSE H.ELM_006 END, 0) as CR_CP,"
				" NVL(CASE WHEN H.ELM_007 = -1 THEN 0 ELSE H.ELM_007 END, 0) as NI_CP,"
				" NVL(CASE WHEN H.ELM_008 = -1 THEN 0 ELSE H.ELM_008 END, 0) as MO_CP"
				" from( select heat_no, end_time, CAST_DIV_NO from tmmsm31"
				" where end_time <= @v_to and end_time >=@v_from) F"
				" left join("
				" select heat_no, ELM_006, ELM_007, ELM_008"
				" from TQMTSB0 b0"
				" where b0.rec_create_time <= @v_to and b0.rec_create_time >=@v_from"
				" )H on F.heat_no = H.heat_no"
				" where 1 = 1"
				" and F.heat_no in("
				" select heat_no from tmmsm21 t2"
				" where  end_time <= @v_to and end_time >=@v_from and st_no != 'DeP' and st_no not like '1%'"
				" union ALL"
				" select heat_no from tmmsm27 t2"
				" where end_time <= @v_to and end_time >=@v_from)) t31 on t31.heat_no = t4.HEAT_NO) t1"
				" left join("
				" select"
				" heat_no,"
				" sum(case when mat_code = 'TS0000' then DEVO_WT else 0 end) as TS0000_DEVO_WT_SUM,"
				" sum(case when dev_code like 'Z%' and TYPE_DL in('合金', '钢铁料') then DEVO_WT else 0 end) as Z_DEV_ALLOY_STEEL_SUM,"
				" sum(case when dev_code like 'Z%' then DEVO_WT * MAT_CR / 100 else 0 end) as Z_DEV_DEVO_MATCR_SUM,"
				" sum(case when dev_code like 'Z%' then DEVO_WT * MAT_NI / 100 else 0 end) as Z_DEV_DEVO_MATNI_SUM,"
				" sum(case when dev_code like 'Z%' then DEVO_WT * MAT_MO / 100 else 0 end) as Z_DEV_DEVO_MATMO_SUM,"
				" sum(case when dev_code like 'E%' and TYPE_DL in('合金', '钢铁料') then DEVO_WT else 0 end) as E_DEV_ALLOY_STEEL_SUM,"
				" sum(case when dev_code like 'E%' then DEVO_WT * MAT_CR / 100 else 0 end) as E_DEV_DEVO_MATCR_SUM,"
				" sum(case when dev_code like 'E%' then DEVO_WT * MAT_NI / 100 else 0 end) as E_DEV_DEVO_MATNI_SUM,"
				" sum(case when dev_code like 'E%' then DEVO_WT * MAT_MO / 100 else 0 end) as E_DEV_DEVO_MATMO_SUM,"
				" sum(case when dev_code like 'A%' and TYPE_DL in('合金', '钢铁料') then DEVO_WT else 0 end) as A_DEV_ALLOY_STEEL_SUM,"
				" sum(case when dev_code like 'A%' then DEVO_WT * MAT_CR / 100 else 0 end) as A_DEV_DEVO_MATCR_SUM,"
				" sum(case when dev_code like 'A%' then DEVO_WT * MAT_NI / 100 else 0 end) as A_DEV_DEVO_MATNI_SUM,"
				" sum(case when dev_code like 'A%' then DEVO_WT * MAT_MO / 100 else 0 end) as A_DEV_DEVO_MATMO_SUM,"
				" sum(case when TYPE_DL in('合金', '钢铁料') then DEVO_WT else 0 end) as Q_DEV_ALLOY_STEEL_SUM,"
				" sum(DEVO_WT * MAT_CR / 100) as Q_DEV_DEVO_MATCR_SUM,"
				" sum(DEVO_WT * MAT_NI / 100) as Q_DEV_DEVO_MATNI_SUM,"
				" sum(DEVO_WT * MAT_MO / 100) as Q_DEV_DEVO_MATMO_SUM,"
				" sum(case when dev_code like 'S%' and TYPE_DL in('辅料') then DEVO_WT else 0 end) as S_DEV_F_MAT_SUM,"
				" sum(case when dev_code like 'F%' and TYPE_DL in('辅料') then DEVO_WT else 0 end) as F_DEV_F_MAT_SUM,"
				" sum(case when dev_code like 'A%' and mat_code = 'AB070665' then DEVO_WT else 0 end) as A_DEV_AB070665_DEVO_WT_SUM,"
				" sum(case when dev_code like 'Z%' and mat_code = 'AB070665' then DEVO_WT else 0 end) as Z_DEV_AB070665_DEVO_WT_SUM"
				" from (select a.heat_no,a.mat_code,a.dev_code,a.QUALITY_BATCH_NO,a.LOT_NO,a.DEVO_WT * 0.001 as DEVO_WT,e.MAT_TYPE_DESC as TYPE_DL,"
				" case when a.lot_no in(select lot_no from TMMSMWQ) then round((select max(cr_VALUE) from TMMSMWQ where lot_no = a.lot_no) *nvl((select INCLUDE_CR from TQMTSCB11_DR where mat_code = a.MAT_CODE), 0), 4)"
				" when a.mat_code in(select MAT_ID from ZJ_MAT_ELEMENT where TYPE = '3') then"
				" (select cr from ZJ_MAT_ELEMENT where TYPE = '3' and MAT_ID = a.MAT_CODE)"
				" when a.mat_code in(select MAT_ID from ZJ_MAT_ELEMENT where TYPE = '1') then"
				" (select cr from ZJ_MAT_ELEMENT where TYPE = '1' and MAT_ID = a.MAT_CODE)"
				" when a.QUALITY_BATCH_NO != ' ' then"
				" nvl((SELECT ELM_VALUE FROM TMMSM81AL"
				" WHERE MAT_CODE = a.MAT_CODE AND ELM_NAME = 'Cr'"
				" and QUALITY_BATCH_NO = a.QUALITY_BATCH_NO), 0)"
				" else"
				" nvl((SELECT ELM_VALUE FROM TMMSM81AL"
				" WHERE MAT_CODE = a.MAT_CODE AND ELM_NAME = 'Cr'"
				" and QUALITY_BATCH_NO in(SELECT MAX(QUALITY_BATCH_NO)"
				" FROM tmmsm81ah"
				" WHERE REC_CREATE_TIME in"
				" (select max(REC_CREATE_TIME)"
				" from tmmsm81ah t2"
				" where t2.MAT_CODE = a.MAT_CODE))), 0)"
				" END MAT_CR,"
				" case when a.lot_no in(select lot_no from TMMSMWQ) then round((select max(Ni_VALUE) from TMMSMWQ where lot_no = a.lot_no) *nvl((select INCLUDE_NI from TQMTSCB11_DR where mat_code = a.MAT_CODE), 0), 4)"
				" when a.mat_code in(select MAT_ID from ZJ_MAT_ELEMENT where TYPE = '4') then"
				" (select NI from ZJ_MAT_ELEMENT where TYPE = '4' and MAT_ID = a.MAT_CODE)"
				" when a.mat_code in(select MAT_ID from ZJ_MAT_ELEMENT where TYPE = '1') then"
				" (select Ni from ZJ_MAT_ELEMENT where TYPE = '1' and MAT_ID = a.MAT_CODE)"
				" when a.QUALITY_BATCH_NO != ' ' then"
				" nvl((SELECT ELM_VALUE FROM TMMSM81AL"
				" WHERE MAT_CODE = a.MAT_CODE AND ELM_NAME = 'Ni'"
				" and QUALITY_BATCH_NO = a.QUALITY_BATCH_NO), 0)"
				" else"
				" nvl((SELECT ELM_VALUE FROM TMMSM81AL"
				" WHERE MAT_CODE = a.MAT_CODE AND ELM_NAME = 'Ni'"
				" and QUALITY_BATCH_NO in(SELECT MAX(QUALITY_BATCH_NO)"
				" FROM tmmsm81ah"
				" WHERE REC_CREATE_TIME in"
				" (select max(REC_CREATE_TIME)"
				" from tmmsm81ah t2"
				" where t2.MAT_CODE = a.MAT_CODE))), 0)"
				" END MAT_NI,"
				" case when a.lot_no in(select lot_no from TMMSMWQ) then round((select max(Mo_VALUE) from TMMSMWQ where lot_no = a.lot_no) *nvl((select INCLUDE_MO from TQMTSCB11_DR where mat_code = a.MAT_CODE), 0), 4)"
				" when a.mat_code in(select MAT_ID from ZJ_MAT_ELEMENT where TYPE = '5') then"
				" (select Mo from ZJ_MAT_ELEMENT where TYPE = '5' and MAT_ID = a.MAT_CODE)"
				" when a.mat_code in(select MAT_ID from ZJ_MAT_ELEMENT where TYPE = '1') then"
				" (select Mo from ZJ_MAT_ELEMENT where TYPE = '1' and MAT_ID = a.MAT_CODE)"
				" when a.QUALITY_BATCH_NO != ' ' then"
				" nvl((SELECT ELM_VALUE FROM TMMSM81AL"
				" WHERE MAT_CODE = a.MAT_CODE AND ELM_NAME = 'Mo'"
				" and QUALITY_BATCH_NO = a.QUALITY_BATCH_NO), 0)"
				" else"
				" nvl((SELECT ELM_VALUE FROM TMMSM81AL"
				" WHERE MAT_CODE = a.MAT_CODE AND ELM_NAME = 'Mo'"
				" and QUALITY_BATCH_NO in(SELECT MAX(QUALITY_BATCH_NO)"
				" FROM tmmsm81ah"
				" WHERE REC_CREATE_TIME in"
				" (select max(REC_CREATE_TIME)"
				" from tmmsm81ah t2"
				" where t2.MAT_CODE = a.MAT_CODE))), 0)"
				" END MAT_MO"
				" from("
				" select heat_no, mat_code, dev_code, QUALITY_BATCH_NO, LOT_NO, DEVO_WT, rec_create_time"
				" from tmmsmgy08 g"
				" where g.rec_create_time <= @v_to and g.rec_create_time >=@v_from"
				" ) a"
				" left join ("
				" select MAT_CODE_DR, MAT_TYPE_DESC, rec_create_time"
				" from tqmtscb08_dr dr"
				" where dr.rec_create_time <= @v_to and dr.rec_create_time >=@v_from"
				" )e on e.MAT_CODE_DR = a.MAT_CODE"
				" where 1 = 1"
				" and exists(select heat_no from tmmsm31 t2 where a.heat_no = t2.heat_no)"
				" and a.heat_no in("
				" select heat_no from tmmsm21 t2"
				" where end_time <= @v_to and end_time >=@v_from and st_no != 'DeP' and st_no not like '1%'"
				" union ALL"
				" select heat_no from tmmsm27 t2 where end_time <= @v_to and end_time >=@v_from"
				" )"
				" ) a_with_mat"
				" group by heat_no"
				" ) a_agg on t1.heat_no = a_agg.heat_no"
				" ) t0_agg"
				" left join("
				" select "
				" heat_no,"
				" ST_NO,"
				" HEATNO_PREMELT1,"
				" HEATNO_PREMELT2,"
				" HEATNO_PREMELT3,"
				" HEATNO_PREMELT4,"
				" LADLE_PRE_LIQUID_WT,"
				" weight_premelt1,"
				" weight_premelt2,"
				" weight_premelt3,"
				" ACTRESULT,"
				" REMARK"
				" from tmmsm27"
				" where end_time <= @v_to and end_time >=@v_from"
				" )t27 on t0_agg.heat_no = t27.heat_no"
				" left join("
				" select"
				" heat_no,"
				" YR_STICKY_WT,"
				" out_end_radio,"
				" is_back_blow,"
				" back_blow_o2,"
				" h_cr_bin_sum"
				" from TMMSM27F f"
				" where f.rec_create_time <= @v_to and f.rec_create_time >=@v_from"
				" )t27f on t0_agg.heat_no = t27f.heat_no"
				" left join ("
				" select ST_NO, SG_GRADE_1"
				" from TQMTS0X q"
				" where q.REC_CREATE_TIME <= @v_to and q.REC_CREATE_TIME >=@v_from"
				" )t0x on t27.ST_NO = t0x.ST_NO"
				" left join ("
				" select HEATNR, f_route1"
				" from tqmtscb02_mx m"
				" where m.aod_bof_e_dtime <= @v_to and m.aod_bof_e_dtime >=@v_from"
				" )tcb on t0_agg.heat_no = tcb.HEATNR"
				" left join ("
				" select heat_no, ACTRESULT"
				" from tmmsm21"
				" where end_time <=  @v_to and end_time >=@v_from"
				" )t21 on t0_agg.heat_no = t21.heat_no"
				" left join ("
				" select heat_no, ACTRESULT, REMARK"
				" from tmmsm20"
				" where end_time <= @v_to and end_time >=@v_from"
				" )t20 on t0_agg.heat_no = t20.heat_no"
				" left join ("
				" select"
				" heat_no,"
				" STEEL_WT,"
				" LADLE_ARRIVE_STEEL_WT,"
				" EMPTY_LADLE_WEIGHT"
				" from tmmsm26"
				" where end_time <= @v_to and end_time >=@v_from"
				" )t26 on t0_agg.heat_no = t26.heat_no"
				" left join ("
				" select heat_no, MOLTIRON_WT, REMARK"
				" from tmmsm24"
				" where end_time <= @v_to and end_time >=@v_from"
				" )t24 on t0_agg.heat_no = t24.heat_no"
				" left join ("
				" select heat_no, deslag_wt1"
				" from ("
				" select"
				" t26f.heat_no,"
				" t26f.deslag_wt1,"
				" t26f.creation_time,"
				" row_number() over (partition by t26f.heat_no order by t26f.creation_time desc) as rn"
				" from TMMSM26F t26f"
				" where t26f.creation_time <= @v_to and t26f.creation_time >=@v_from"
				" )"
				" where rn = 1"
				" )t26f on t0_agg.heat_no = t26f.heat_no"
				" left join("
				" select"
				" heat_no,"
				" CASE WHEN ELM_006 = -1 THEN 0 ELSE ELM_006 END as CR_1,"
				" CASE WHEN ELM_007 = -1 THEN 0 ELSE ELM_007 END as NI_1,"
				" CASE WHEN ELM_008 = -1 THEN 0 ELSE ELM_008 END as MO_1"
				" from ("
				" select"
				" t24.heat_no,"
				" t24.ELM_006,"
				" t24.ELM_007,"
				" t24.ELM_008,"
				" t24.REC_CREATE_TIME,"
				" row_number() over(partition by t24.heat_no order by t24.REC_CREATE_TIME desc) as rn"
				" from TQMTS24 t24"
				" where  rec_create_time <= @v_to and rec_create_time >=@v_from AND ST_SAMPLE_DIV = 'T'"
				" and WHOLE_BACKLOG_CODE = 'A'"
				" and SAMPLE_TYPE = '1'"
				" and SAMPLE_IFGOOD = '0'"
				" )"
				" where rn = 1"
				" ) t24_cr_ni_mo on t0_agg.heat_no = t24_cr_ni_mo.heat_no"
				" left join ("
				" select"
				" heat_no,"
				" CASE WHEN ELM_002 = -1 THEN 0 ELSE ELM_002 END as SI_2"
				" from ("
				" select"
				" t24.heat_no,"
				" t24.ELM_002,"
				" t24.REC_CREATE_TIME,"
				" row_number() over(partition by t24.heat_no order by t24.REC_CREATE_TIME desc) as rn"
				" from TQMTS24 t24"
				" where rec_create_time <= @v_to and rec_create_time >=@v_from AND ST_SAMPLE_DIV = 'S'"
				" and WHOLE_BACKLOG_CODE = 'A'"
				" and SAMPLE_TYPE = '2'"
				" and ST_SAMPLE_SEQ = '1'"
				" and SAMPLE_IFGOOD = '0'"
				" )"
				" where rn = 1"
				" ) t24_si2 on t0_agg.heat_no = t24_si2.heat_no"
				" left join("
				" select"
				" heat_no,"
				" CASE WHEN ELM_002 = -1 THEN 0 ELSE ELM_002 END as SI_3"
				" from ("
				" select"
				" t24.heat_no,"
				" t24.ELM_002,"
				" t24.REC_CREATE_TIME,"
				" row_number() over(partition by t24.heat_no order by t24.REC_CREATE_TIME desc) as rn"
				" from TQMTS24 t24"
				" where rec_create_time <=  @v_to and rec_create_time >=@v_from AND ST_SAMPLE_DIV = 'T'"
				" and WHOLE_BACKLOG_CODE = 'A'"
				" and SAMPLE_TYPE = '3'"
				" and SAMPLE_IFGOOD = '0'"
				" )"
				" where rn = 1"
				" ) t24_si3 on t0_agg.heat_no = t24_si3.heat_no order by t0_agg.LADLE_CLOSE_TIME desc";
			Log::Trace("", __FUNCTION__, "sqlstr[{0}]  ", sqlstr);
			Log::Trace("", __FUNCTION__, "sqlstr[{0}]  ", v_from);
			Log::Trace("", __FUNCTION__, "sqlstr[{0}]  ", v_to);
			cmd_inq.SetCommandText(sqlstr);

			
			cmd_inq.Parameters.Set("v_from", v_from);
			cmd_inq.Parameters.Set("v_to", v_to);
			cmd_inq.ExecuteQuery(bcls_ret->Tables[0]);
			cmd_inq.Close();
		}


	}
	catch (CDbException& ex)  //捕获数据库操作异常
	{
		CFormattable arguments[] = { ex.GetCode() };
		CMessageFormat::Format(s.msg, _RES("GCRSS0000006")/*数据库处理出错，sqlcode=[{0}]。请联系系统维护人员。*/, arguments, 1);
		CString str = sqlstr + "\r\n" + ex.GetMsg();
		strncpy(s.sysmsg, (const char*)str, sizeof(s.sysmsg) - 1);  //返回前台，与EI.EIInfo对象的sys_info.sysmsg参数对应
		s.flag = -1;
		doFlag = -1;                 //数据库异常时返回-1，事务将被回滚
	}
	catch (CApplicationException& ex)  //捕获应用错误
	{
		s.flag = ex.GetCode();
		doFlag = -1;
	}
	catch (CException& ex)
	{

		strncpy(s.msg, (const char*)ex.GetMsg(), sizeof(s.msg) - 1);
		s.flag = ex.GetCode();
		doFlag = -1;
	}
	cmd_inq.Close();
	//返回-1时事务将回滚，返回为0是事务将提交
	return doFlag;
}